---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
  - name: Install Docker dependencies
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Install Docker
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
    notify: restart docker

  - name: Updating Docker cgroup on Master Node
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
         "exec-opts": ["native.cgroupdriver=systemd"]
        }

  - name: Add user to Docker group
    user:
      name: labsuser
      groups: docker
      append: yes

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
