---
- name: Install Kubernetes master and worker
  hosts: all
  become: true
  tasks:

   - name: Make the Swap inactive
     command: swapoff -a

   - name: Remove Swap entry from /etc/fstab.
     lineinfile:
       dest: /etc/fstab
       regexp: swap
       state: absent

   - name: Installing Prerequisites for Kubernetes
     apt:
       name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - vim
         - software-properties-common
       state: present

   - name: Add Google official GPG key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present
       
   - name: Add Kubernets apt repository
     command: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

   - name: Install kubeadm, kubelet, kubectl
     apt:
       name:
         - kubeadm
         - kubectl
         - kubelet
       state: present
   
   - name: Enable service kubelet, and enable persistently
     service:
       name: kubelet
       state: started
       enabled: yes
     notify: restart kubelet
   
   - name: Pull Kubernetes container images
     command: kubeadm config images pull
     
   - name: Initialize Kubernetes cluster on master
     command: kubeadm init --ignore-preflight-errors=all --v=5
     when: "'master' in group_names"

   - name: Making user directory to store Kubernetes config
     shell: mkdir -p $HOME/.kube
     when: "'master' in group_names"

  handlers:
   - name: restart kubelet
     service:
       name: kubelet
       state: restarted
