apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
    role: backend
  name: postgres
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      role: backend
  template:
    metadata:
      labels:
        app: db
        role: backend
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: pwd
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
